version: '3'

# The network that all the different containers will use to communicate with eachother.
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped # Retart container if not manually stopped.
    tty: true # Allows the use of a shell like interface if needed.
    ports:
      - "3306:3306"
    volumes: # Prevents the database from getting destroyed when the docker is destroyed.
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: checkmate
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  # Can't use a php image as it doesn't include PDO which Laravel requires.
  php:
    build:
      context: .
      dockerfile: Dockerfile # The file we are building from.
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:12.13
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel