version: '3'

  # The java test container. This container is made with a maven image.
services:
  maven:
    image: maven:3.6.2-jdk-8
    container_name: maven
    volumes:
      - ./kits/java:/var/www/html/
    working_dir: /var/www/html/